App:
  LastLeft: Dashboard
  Version: V1.0
Blueprints:
  Bites:
    Enabled: true
  Enabled: true
  Moodifier:
    Enabled: true
C++:
  Bites:
    Enabled: true
  Enabled: true
  PopUps:
    AutoCloseAfter: 10
    Enabled: false
  Type:
    DelayBetweenCharacters: 0.1
    Enabled: true
    LogTypeHistory: true
Misc:
  ProjectDirectory: ''
  XattrBot: false
