App:
  LastLeft: C++
Blueprints:
  Bites:
    Enabled: true
  Enabled: true
C++:
  Bites:
    Enabled: true
  Enabled: true
  PopUps:
    AutoCloseAfter: -1
    Enabled: true
  Type:
    DelayBetweenCharacters: 1
    Enabled: true
    LogTypeHistory: true
