App:
  LastLeft: C++
  Version: V1.0
Blueprints:
  Bites:
    Enabled: true
  Enabled: true
  Moodifier:
    Enabled: true
C++:
  Bites:
    Enabled: true
  Enabled: true
  PopUps:
    AutoCloseAfter: 10
    Enabled: true
  Type:
    DelayBetweenCharacters: 1.0
    Enabled: true
    LogTypeHistory: true
Misc:
  ProjectDirectory: ''
  XattrBot: false
