App:
  LastLeft: Info
  Version: V2.0
Blueprints:
  Bites:
    Enabled: true
  Enabled: false
  Moodifier:
    Enabled: true
C++:
  Bites:
    Enabled: true
  Enabled: true
  PopUps:
    AutoCloseAfter: 5.88
    Enabled: true
  Type:
    DelayBetweenCharacters: 1
    Enabled: true
    LogTypeHistory: true
